name: pirate
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  flutter_dynamic_icon: ^2.1.0
  flutter_exit_app: ^1.1.2
  flutter_inappwebview: ^5.7.2+3
  flutter_screenutil: ^5.9.0
  overlay_support: ^2.1.0
  in_app_review: ^2.0.6
  firebase_messaging: ^14.2.2
  firebase_core: ^2.21.0
  firebase_remote_config: ^4.3.3
  flutter_local_notifications: ^9.8.0+1
  flutter_svg: ^2.0.9
  get: ^4.6.6
  get_it: ^7.6.7
  kbspinningwheel: ^1.0.3
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  stroke_text: ^0.0.2
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/reward/
    - assets/items/
    - assets/main/
    - assets/roulette/
    - assets/spots/
  fonts:
    - family: RammettoOne
      fonts:
        - asset: assets/fonts/Rammetto_One/RammettoOne-Regular.ttf
    - family: Schoolbell
      fonts:
        - asset: assets/fonts/Schoolbell/Schoolbell-Regular.ttf
